### ISSUE TITLE
why can not save the payload that has been made, modulecp: cannot stat 'tmp/Vidmate-injected.apk': No such file or directory

### ISSUE THREAD

**Issue by mazkeplen19** [saydog-official/saydog-framework#2]
How to fix?

**Comment by saydog-official** [comment]
> How to fix?

Just execute this commands:
$ saydog error

**Comment by mazkeplen19** [comment]
already but still can't, how to fix?



Pada tanggal Sel, 23 Jun 2020 11.59 AM SAYDOG OFFICIAL <
notifications@github.com menulis:
